import type { Metadata } from "next";
import ClientProviders from "@/components/ClientProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tinta - Generate Palettes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased max-w-screen-xl md:mx-auto mx-8"}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
